version: "3.8"
services:
  db:
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
        - "3306:3306"
    volumes:
        - db_data:/var/lib/mysql
    networks:
      - internal
      - proxy

volumes:
    db_data:
networks:
    internal:
      external: false
    proxy:
        external: true


